### ISSUE TITLE
XML error

### ISSUE THREAD

**Issue by Hellomik2002** [PeculiarVentures/node-webcrypto-p11#57]
I installed webcrypto with npm by but still have issue, when I try  new XmlDSigJs.SignedXml().Sign(...)
```
XmlError {
  prefix: 'XMLJS',
  code: 14,
  name: 'XmlError',
  message: 'XMLJS0014: WebCrypto module is not found',
  stack: 'Error: XMLJS0014: WebCrypto module is not found\n' +
    '    at new XmlError (C:\\projects\\notr\\node_modules\\xml-core\\dist\\index.js:216:22)\n' +
    '    at Function.get crypto [as crypto] (C:\\projects\\notr\\node_modules\\xmldsigjs\\build\\index.js:22:19)\n' +
    '    at RsaKeyValue.importKey (C:\\projects\\notr\\node_modules\\xmldsigjs\\build\\index.js:1539:39)\n' +
    '    at KeyValue.importKey (C:\\projects\\notr\\node_modules\\xmldsigjs\\build\\index.js:1710:34)\n' +
    '    at SignedXml.ApplySignOptions (C:\\projects\\notr\\node_modules\\xmldsigjs\\build\\index.js:2656:28)\n' +
    '    at SignedXml.Sign (C:\\projects\\notr\\node_modules\\xmldsigjs\\build\\index.js:2360:20)\n' +
    '    at C:\\projects\\notr\\cryptXML.js:59:22'
}
```

**Comment by rmhrisk** [comment]
Dupe
