### ISSUE TITLE
Ubuntu 14.04.2 LTS installation

### ISSUE THREAD

**Issue by l-ko** [PeculiarVentures/node-webcrypto-p11#7]
```
apt-get install softhsm
```
installs successfully.

```
softhsm2-util --init-token --slot 0 --label "My token 1"
softhsm2-util: command not found
```
Probably because it is installed with *softhsm* command.
```
softhsm --init-token --slot 0 --label "My token 1"The SO PIN must have a length between 4 and 255 characters.
Enter SO PIN: 
The user PIN must have a length between 4 and 255 characters.
Enter user PIN: 
Error: The token is not present.
Error: Probably missing write permissions, please check the path and file given in the configuration.
```
Checking configuration file at /etc/softhsm/softhsm.conf:
```
# SoftHSM configuration file
#
# Format:
# <Slot ID>:<Path to the token database>
#
# The given paths are just an indication to SoftHSM on where it should
# store the information for each token.

0:/var/lib/lib/softhsm/slot0.db
```
Removing one of the 'lib' in path (I guess it was used instead of 'local' for some reason, see further problems)
```
sudo chmod 755 -R /var/lib/softhsm
```
OK
```
sudo chmod 755 -R /usr/lib/softhsm
```
NOTE that I removed 'local' from the path
```
chown root:softhsmusers /var/lib/softhsm/
chown: invalid group: ‘root:softhsmusers’
...
chown root:softhsm /var/lib/softhsm/
chown root:softhsm /usr/lib/softhsm/
```
OK
```
npm install
cd node_modules/
rm -rf graphene-pk11/
git clone https://github.com/PeculiarVentures/graphene.git graphene-pk11
cd graphene-pk11/
npm install
```
OK
```
cd ../../
mocha
Aes
    1) "before all" hook
    2) "after all" hook

  EC
    3) "before all" hook
    4) "after all" hook

  RSA
    5) "before all" hook
    6) "after all" hook

  Subtle
    7) "before all" hook
    8) "after all" hook


  0 passing (137ms)
  8 failing

1) Aes "before all" hook:
     Error: ENOENT: no such file or directory, open '/usr/local/lib/softhsm/libsofthsm2.so'
      at Error (native)
      at Object.fs.openSync (fs.js:584:18)
      at fs.readFileSync (fs.js:431:33)
      at new DynamicLibrary (node_modules/graphene-pk11/node_modules/ffi/lib/dynamic_library.js:67:21)
      at Object.Library (node_modules/graphene-pk11/node_modules/ffi/lib/library.js:45:12)
      at new Pkcs11 (node_modules/graphene-pk11/build/pkcs11/pkcs11.js:14:24)
      at Function.Module.load (node_modules/graphene-pk11/build/module.js:70:19)
      at new WebCrypto (built/webcrypto.js:7:56)
      at Context.<anonymous> (test/aes.js:20:21)

  2) Aes "after all" hook:
     TypeError: Cannot read property 'close' of undefined
      at Context.<anonymous> (test/aes.js:26:18)

  3) EC "before all" hook:
     Error: ENOENT: no such file or directory, open '/usr/local/lib/softhsm/libsofthsm2.so'
      at Error (native)
      at Object.fs.openSync (fs.js:584:18)
      at fs.readFileSync (fs.js:431:33)
      at new DynamicLibrary (node_modules/graphene-pk11/node_modules/ffi/lib/dynamic_library.js:67:21)
      at Object.Library (node_modules/graphene-pk11/node_modules/ffi/lib/library.js:45:12)
      at new Pkcs11 (node_modules/graphene-pk11/build/pkcs11/pkcs11.js:14:24)
      at Function.Module.load (node_modules/graphene-pk11/build/module.js:70:19)
      at new WebCrypto (built/webcrypto.js:7:56)
      at Context.<anonymous> (test/ec.js:21:21)
...
```
Note how it tries to find lib with 'local' in the path, while the real path after installation is /usr/lib/softhsm/libsofthsm2,so

**Comment by l-ko** [comment]
'apt-get install softhsm' installs the 1st version, but the 2nd is needed, in order to install:
https://github.com/opendnssec/SoftHSMv2
```
apt-get install autogen autoconf libtool
git clone https://github.com/opendnssec/SoftHSMv2.git
cd SoftHSMv2/
h ./autogen.sh
./configure
make
sudo make install
```
```
mocha tests
  Aes
    1) Aes GCM
    ✓ Aes CBC encrypt/decrypt
    ✓ Aes export/import JWK
    ✓ AES import/export RAW
    ✓ AES wrap/unwrap JWK
    ✓ AES wrap/unwrap raw

  EC
    2) Ecdsa
    ✓ ECDSA JWK export/import
    ✓ Ecdh

  RSA
    ✓ RSA generate (83ms)
    ✓ RSA PKCS1 JWK export/import
    ✓ RSA PKCS1 1.5 sign/verify
    3) RSA OAEP encrypt/decrypt
    4) RSA OAEP wrap/unwrap JWK
    ✓ RSA OAEP wrap/unwrap RAW

  Subtle
    ✓ random
    ✓ Digest SHA-1
    ✓ Digest SHA-224
    ✓ Digest SHA-256
    ✓ Digest SHA-384
    ✓ Digest SHA-512


  17 passing (589ms)
  4 failing
```
